export const MOCKUP_DATA = [
  {
    id: 1,
    title: '첫 번째 게시글',
    content:
      '이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다.  이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다. 이것은 첫 번째 게시글의 내용입니다.커뮤니티에서 다양한 이야기를 나누어보세요. 이것은 첫 번째 게시글의 내용입니다. 커뮤니티에서 다양한 이야기를 나누어보세요. 이것은 첫 번째 게시글의 내용입니다. 커뮤니티에서 다양한 이야기를 나누어보세요. 이것은 첫 번째 게시글의 내용입니다. 커뮤니티에서 다양한 이야기를 나누어보세요. 이것은 첫 번째 게시글의 내용입니다. 커뮤니티에서 다양한 이야기를 나누어보세요. 이것은 첫 번째 게시글의 내용입니다. 커뮤니티에서 다양한 이야기를 나누어보세요.',
    imageUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop',
    like: 10,
    comment: 5,
    isLiked: false,
    date: '25.09.01',
  },
  {
    id: 2,
    title: '일상 공유',
    content: '오늘 하루는 어땠나요? 특별한 순간이나 재미있는 일이 있었다면 함께 나누어봐요.',
    like: 15,
    comment: 8,
    isLiked: true,
    date: '25.09.01',
  },
  {
    id: 3,
    title: '배움의 기록',
    content: '새로 배운 기술이나 지식이 있다면 공유해주세요. 함께 성장해나가요!',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop',
    like: 23,
    comment: 12,
    isLiked: false,
    date: '25.08.31',
  },
  {
    id: 4,
    title: '취미 생활',
    content: '요즘 즐기고 있는 취미가 있나요? 독특한 취미나 새로운 도전을 해보고 있어요.',
    like: 7,
    comment: 3,
    isLiked: false,
    date: '25.08.31',
  },
  {
    id: 5,
    title: '맛집 추천',
    content:
      '최근에 가본 맛집이나 추천하고 싶은 식당이 있다면 알려주세요. 음식 이야기도 재미있어요.',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',
    like: 31,
    comment: 18,
    isLiked: true,
    date: '25.08.30',
  },
  {
    id: 6,
    title: '여행 후기',
    content: '여행 다녀온 곳이나 가고 싶은 곳이 있다면 이야기해보세요. 여행 팁도 공유해주세요.',
    like: 19,
    comment: 9,
    isLiked: false,
    date: '25.08.30',
  },
  {
    id: 7,
    title: '책 추천',
    content: '최근에 읽은 책 중에서 추천하고 싶은 책이 있나요? 독서 후기도 함께 나누어보세요.',
    like: 12,
    comment: 6,
    isLiked: false,
    date: '25.08.29',
  },
  {
    id: 8,
    title: '일과 삶의 균형',
    content: '바쁜 일상 속에서 어떻게 삶의 균형을 맞추고 계신가요? 조언이나 경험을 나누어주세요.',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    like: 28,
    comment: 15,
    isLiked: true,
    date: '25.08.29',
  },
];
